### ISSUE TITLE
Displaying grouped results

### ISSUE THREAD

**Issue by rleonid** [janestreet/core_bench#10]
I was a bit surprised that `Test.create_group` doesn't actually result in displaying those grouped tests individually. Is there a way to achieve that functionality short of writing different tests?

**Comment by roshanjames** [comment]
Sorry for the late reply.

[Test.create_group] does the simple thing of just attaching a given prefix to all the tests, so that they tend to group together in the output table. 

Do you want to see the results of each group of tests in a separate ascii table? There is nothing built into bench that does that currently. 

You could try and customize the command line of your benchmarking program to accept a regex or something similar such that you can filter out the tests the you care about from the command line. This may help you pick and choose from a large body of tests. I've attached an example of how you'd do this. Hope that helps.
[z.ml.txt](https://github.com/janestreet/core_bench/files/649553/z.ml.txt)

**Comment by rleonid** [comment]
Gotcha. I thought it might be more useful to have grouping of tests denote which tests are actually comparable. So one could have a group of my "addition" method and another for my "multiplication" method. But having multiple applications, different `command`'s also seems fine. I'll close the issue, but not this as  feature request.
