### ISSUE TITLE
Passing -sexp causes a crash: Invalid_argument "List.nth_exn 1 called on list of length 1"

### ISSUE THREAD

**Issue by cpitclaudel** [janestreet/core_bench#14]
Hi,

Thanks for this neat library.
I'm trying to plot measurements, and for that I'd like to export results in a machine-friendly format.  Passing -sexp, however, crashes the benchmark.  Here is a small repro:

*miminal.ml*:

```ocaml
open Core_bench.Std

let () =
  Core.Command.run (Bench.make_command [
    Bench.Test.create ~name:"id"
      (fun () -> ());
  ])
```

*minimal.sh*:

```bash
#!/usr/bin/env sh
ocamlfind ocamlopt -linkpkg -thread -package core -package core_bench minimal.ml -o minimal || exit 1
./minimal -sexp
```

*Output:*

```
Uncaught exception:
  
  (Invalid_argument "List.nth_exn 1 called on list of length 1")

Raised at file "pervasives.ml", line 33, characters 25-45
Called from file "src/simplified_benchmark.ml", line 102, characters 14-78
Called from file "src/simplified_benchmark.ml", line 123, characters 36-65
Called from file "src/list.ml", line 318, characters 13-17
Called from file "src/list.ml", line 346, characters 15-31
Called from file "src/simplified_benchmark.ml", line 183, characters 2-26
Called from file "src/command.ml", line 2529, characters 6-97
Called from file "src/exn.ml", line 110, characters 6-10
```

Am I doing something wrong?

**Comment by cshardin** [comment]
Thanks for catching this.  We've just released a fix internally so I assume the next public release will have the fix.  In the meantime, a workaround is to use something like `~name:"[foo.ml] id"` because the code in question was (incorrectly) assuming the name would be formatted that way.

Are you trying to export the measurements (many rows of data for each benchmark, where each row has the number of times the function was called in that batch, how long the batch took to run, how many minor words were allocated, etc.) or the results of the regression run on that data (i.e., the information printed to stdout when you run the benchmark)?  If it's the latter, then the -sexp flag is indeed what you want, but if it's the former, you should use the -save flag.

**Comment by cpitclaudel** [comment]
>  In the meantime, a workaround is to use something like ~name:"[foo.ml] id" because the code in question was (incorrectly) assuming the name would be formatted that way.

Thanks!

>  If it's the latter, then the -sexp flag is indeed what you want, but if it's the former, you should use the -save flag.

It's indeed the latter — I'm interested in plotting the results :)

**Comment by vyorkin** [comment]
Hello, I want to help with the PR, but I need some guidance.
So, if I understand correctly, the following function needs to be updated, right?
https://github.com/janestreet/core_bench/blob/f483ba9eeee22e3cdbc1e61896892e8c8941d0b5/src/simplified_benchmark.ml#L104

Btw, can we just remove it along with the `benchmark_name_with_index` field? I didn't find any use of it.

**Comment by hhugo** [comment]
This was fixed last year https://github.com/janestreet/core_bench/commit/0fd141400c03cd9e796610fb8c2d07bfe8d6555c#diff-ae15fa2dc0ad4c2f29034381713409be
unless I'm missing something

**Comment by vyorkin** [comment]
Oh, you're right. Haven't noticed that. Thanks!
